name: Python CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Especifica la máquina base
    container:
      image: python:3.9  # Especifica la imagen Docker para ejecutar el trabajo

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pylint
        run: |
          pip install pylint
          pylint **/*.py

      - name: Run tests and coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=.
