name: Python CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Máquina base para ejecutar el contenedor Docker
    container:
      image: python:3.9  # Imagen Docker para ejecutar el flujo de trabajo

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pylint for static code analysis
        run: |
          pip install pylint
          pylint **/*.py

      - name: Run tests and check coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=.
